'use strict';
const https=require('node:https');const {createSupabaseOrderProofStore}=require('./engine/order-proof-store.cjs');const {createSupabaseCommerceEventStore}=require('./engine/commerce-event-store.cjs');const {createSupabaseCommerceOutcomeStore}=require('./engine/commerce-outcome-store.cjs');const {verifyUnasOrder}=require('./engine/unas-order-verifier.cjs');const {reprocessVerifiedOrder}=require('./engine/verified-order-reprocess.cjs');
const SAFE_OPERATIONS=new Set(['commerce_order_proof_lookup','commerce_attribution_lookup','commerce_product_clicked_lookup','commerce_outcome_insert','commerce_outcome_lookup']);
function category(status,operation){if(status===401)return'SUPABASE_AUTH_FAILED';if(status===403)return'SUPABASE_PERMISSION_DENIED';if(status===404)return operation?.includes('rpc')?'SUPABASE_RPC_NOT_FOUND':'SUPABASE_TABLE_NOT_FOUND';if(status===400||status===406||status===409||status===422)return'SUPABASE_BAD_REQUEST';if(status===0)return'SUPABASE_NETWORK_FAILED';return'SUPABASE_UNKNOWN_REQUEST_FAILED';}
function failure(status,operation){const error=new Error('supabase_request_failed');error.code=category(status,operation);error.safeStatus=Number.isInteger(status)?status:0;error.safeOperation=SAFE_OPERATIONS.has(operation)?operation:'unknown';return error;}
function authHeaders(key){const value=String(key||'');if(!value)throw Object.assign(new Error('supabase_runtime_required'),{code:'SUPABASE_RUNTIME_REQUIRED'});return value.startsWith('sb_secret_')?{apikey:value}:{apikey:value,Authorization:`Bearer ${value}`};}
function request({method='GET',pathname,body,headers={},operation}){const base=String(process.env.SUPABASE_URL||'').replace(/\/+$/,''),key=String(process.env.SUPABASE_SERVICE_ROLE_KEY||'');if(!base||!key)throw Object.assign(new Error('supabase_runtime_required'),{code:'SUPABASE_RUNTIME_REQUIRED'});const url=new URL(pathname,`${base}/`),payload=body===undefined?null:JSON.stringify(body);return new Promise((resolve,reject)=>{const req=https.request(url,{method,headers:{...authHeaders(key),'Content-Type':'application/json',...(payload?{'Content-Length':Buffer.byteLength(payload)}:{}),...headers}},res=>{let text='';res.setEncoding('utf8');res.on('data',c=>text+=c);res.on('end',()=>res.statusCode>=200&&res.statusCode<300?resolve({status:res.statusCode,headers:res.headers,body:text}):reject(failure(Number(res.statusCode)||0,operation)));});req.on('error',()=>reject(failure(0,operation)));if(payload)req.write(payload);req.end();});}
async function main(){try{const result=await reprocessVerifiedOrder({proofStore:createSupabaseOrderProofStore({request}),eventStore:createSupabaseCommerceEventStore({request}),outcomeStore:createSupabaseCommerceOutcomeStore({request}),verifyOrder:verifyUnasOrder});console.log(`ORDER_REPROCESS: ${result.ok?'PASS':'FAIL'}`);console.log(`OUTCOME: ${result.duplicate?'EXISTING_OR_DUPLICATE':'CREATED'}`);}catch(error){const code=/^[A-Z0-9_]{1,80}$/.test(String(error?.code||''))?error.code:'SANITIZED_REPROCESS_FAILURE';console.log(`STOP: ${code}`);if(error?.safeOperation)console.log(`SUPABASE_OPERATION: ${error.safeOperation}`);if(Number.isInteger(error?.safeStatus))console.log(`HTTP_STATUS: ${error.safeStatus}`);process.exitCode=1;}}
if(require.main===module)main();

module.exports={SAFE_OPERATIONS,authHeaders,category,failure,main};
