'use strict';
const https=require('node:https');const {createSupabaseOrderProofStore}=require('./engine/order-proof-store.cjs');const {createSupabaseCommerceEventStore}=require('./engine/commerce-event-store.cjs');const {createSupabaseCommerceOutcomeStore}=require('./engine/commerce-outcome-store.cjs');const {verifyUnasOrder}=require('./engine/unas-order-verifier.cjs');const {reprocessVerifiedOrder}=require('./engine/verified-order-reprocess.cjs');
const SAFE_OPERATIONS=new Set(['commerce_order_proof_lookup','commerce_attribution_lookup','commerce_product_clicked_lookup','commerce_outcome_insert','commerce_outcome_lookup']);
function category(status,operation){if(status===401)return'SUPABASE_AUTH_FAILED';if(status===403)return'SUPABASE_PERMISSION_DENIED';if(status===404)return operation?.includes('rpc')?'SUPABASE_RPC_NOT_FOUND':'SUPABASE_TABLE_NOT_FOUND';if(status===400||status===406||status===409||status===422)return'SUPABASE_BAD_REQUEST';if(status===0)return'SUPABASE_NETWORK_FAILED';return'SUPABASE_UNKNOWN_REQUEST_FAILED';}
function failure(status,operation){const error=new Error('supabase_request_failed');error.code=category(status,operation);error.safeStatus=Number.isInteger(status)?status:0;error.safeOperation=SAFE_OPERATIONS.has(operation)?operation:'unknown';return error;}
function authHeaders(key){const value=String(key||'');if(!value)throw Object.assign(new Error('supabase_runtime_required'),{code:'SUPABASE_RUNTIME_REQUIRED'});return value.startsWith('sb_secret_')?{apikey:value}:{apikey:value,Authorization:`Bearer ${value}`};}
function request({method='GET',pathname,body,headers={},operation}){const base=String(process.env.SUPABASE_URL||'').replace(/\/+$/,''),key=String(process.env.SUPABASE_SERVICE_ROLE_KEY||'');if(!base||!key)throw Object.assign(new Error('supabase_runtime_required'),{code:'SUPABASE_RUNTIME_REQUIRED'});const url=new URL(pathname,`${base}/`),payload=body===undefined?null:JSON.stringify(body);return new Promise((resolve,reject)=>{const req=https.request(url,{method,headers:{...authHeaders(key),'Content-Type':'application/json',...(payload?{'Content-Length':Buffer.byteLength(payload)}:{}),...headers}},res=>{let text='';res.setEncoding('utf8');res.on('data',c=>text+=c);res.on('end',()=>res.statusCode>=200&&res.statusCode<300?resolve({status:res.statusCode,headers:res.headers,body:text}):reject(failure(Number(res.statusCode)||0,operation)));});req.on('error',()=>reject(failure(0,operation)));if(payload)req.write(payload);req.end();});}
function urlDiagnostic(value){try{const parsed=new URL(String(value||''));const match=/^([a-z0-9]{20})\.supabase\.co$/.exec(parsed.hostname);if(parsed.protocol!=='https:'||!match||!/^\/?$/.test(parsed.pathname)||parsed.search||parsed.hash)return{format:'INVALID',ref:null,masked:'NONE'};const ref=match[1];return{format:'VALID',ref,masked:`${ref.slice(0,4)}...${ref.slice(-4)}`};}catch{return{format:'INVALID',ref:null,masked:'NONE'};}}
function keyDiagnostic(value){const key=String(value||'');if(key.startsWith('sb_secret_'))return{type:'SB_SECRET',ref:null};if(!key.startsWith('eyJ'))return{type:'UNKNOWN',ref:null};try{const payload=JSON.parse(Buffer.from(key.split('.')[1]||'','base64url').toString('utf8'));return{type:'LEGACY_JWT',ref:typeof payload.ref==='string'?payload.ref:null,role:payload.role};}catch{return{type:'LEGACY_JWT',ref:null};}}
async function runAuthDiagnostic({url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY,probe=request}={}){const urlInfo=urlDiagnostic(url),keyInfo=keyDiagnostic(key);let status=0,result='UNKNOWN';if(urlInfo.format==='VALID'&&keyInfo.type!=='UNKNOWN'){if(keyInfo.type==='LEGACY_JWT'&&keyInfo.ref&&keyInfo.ref!==urlInfo.ref){result='PROJECT_KEY_MISMATCH';}else{try{const response=await probe({method:'GET',pathname:'/rest/v1/',operation:'supabase_auth_probe'});status=Number(response?.status)||0;result=status>=200&&status<300?'PASS':'UNKNOWN';}catch(error){status=Number(error?.safeStatus)||0;if(status===401&&keyInfo.type==='LEGACY_JWT'&&keyInfo.ref===urlInfo.ref)result='INVALID_KEY';}}}return{keyType:keyInfo.type,urlFormat:urlInfo.format,maskedRef:urlInfo.masked,status,result};}
async function diagnosticMain(){const result=await runAuthDiagnostic();console.log(`SUPABASE_KEY_TYPE: ${result.keyType}`);console.log(`SUPABASE_URL_FORMAT: ${result.urlFormat}`);console.log(`PROJECT_REF_FROM_URL: ${result.maskedRef}`);console.log(`AUTH_PROBE_STATUS: ${result.status}`);console.log(`AUTH_PROBE_RESULT: ${result.result}`);if(result.result!=='PASS')process.exitCode=1;}
const UNAS_STEPS=new Set(['UNAS_LOGIN','UNAS_GET_ORDER','ORDER_COUNT','ORDER_KEY_MATCH','ORDER_ID_PRESENT','SKU_MATCH']);const UNAS_CATEGORIES=new Set(['LOGIN_FAILED','NETWORK_FAILED','GET_ORDER_FAILED','ORDER_NOT_FOUND','MULTIPLE_ORDERS','ORDER_KEY_MISMATCH','ORDER_ID_MISSING','SKU_MISMATCH','MALFORMED_RESPONSE','UNKNOWN_UNAS_FAILURE']);
function printUnasDiagnostic(event){const step=UNAS_STEPS.has(event?.step)?event.step:'UNAS_GET_ORDER',result=event?.result==='PASS'?'PASS':'FAIL',status=Number.isInteger(event?.status)?event.status:'NONE';console.log(`UNAS_STEP: ${step}`);console.log(`UNAS_RESULT: ${result}`);console.log(`UNAS_HTTP_STATUS: ${status}`);if(result==='FAIL')console.log(`UNAS_ERROR_CATEGORY: ${UNAS_CATEGORIES.has(event?.category)?event.category:'UNKNOWN_UNAS_FAILURE'}`);}
async function main(){try{const onUnasDiagnostic=printUnasDiagnostic;const result=await reprocessVerifiedOrder({proofStore:createSupabaseOrderProofStore({request}),eventStore:createSupabaseCommerceEventStore({request}),outcomeStore:createSupabaseCommerceOutcomeStore({request}),verifyOrder:orderKey=>verifyUnasOrder(orderKey,{onDiagnostic:onUnasDiagnostic}),onUnasDiagnostic});console.log(`ORDER_REPROCESS: ${result.ok?'PASS':'FAIL'}`);console.log(`OUTCOME: ${result.duplicate?'EXISTING_OR_DUPLICATE':'CREATED'}`);}catch(error){const code=/^[A-Z0-9_]{1,80}$/.test(String(error?.code||''))?error.code:'SANITIZED_REPROCESS_FAILURE';console.log(`STOP: ${code}`);if(error?.safeOperation)console.log(`SUPABASE_OPERATION: ${error.safeOperation}`);if(Number.isInteger(error?.safeStatus))console.log(`HTTP_STATUS: ${error.safeStatus}`);process.exitCode=1;}}
if(require.main===module)(process.argv.includes('--diagnose-auth')?diagnosticMain():main());

module.exports={SAFE_OPERATIONS,authHeaders,category,failure,keyDiagnostic,main,printUnasDiagnostic,runAuthDiagnostic,urlDiagnostic};
