create table if not exists public.chat_conversations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id text not null,
  question text not null,
  answer text not null,
  confidence double precision,
  matched_knowledge_ids jsonb not null default '[]'::jsonb,
  source text,
  response_ms integer,
  user_agent text,
  page_url text
);
create index if not exists chat_conversations_created_at_idx on public.chat_conversations(created_at desc);
create index if not exists chat_conversations_session_id_idx on public.chat_conversations(session_id);
