'use strict';
const assert=require('assert'),fs=require('fs'),http=require('http'),path=require('path');const{spawn}=require('child_process');
const PORT=3399,TOKEN='knowledge-task-api-test',ROOT=__dirname,taskPath=path.join(ROOT,'data','logs','knowledge-tasks.jsonl'),draftPath=path.join(ROOT,'data','logs','knowledge-drafts.jsonl'),pidPath=path.join(ROOT,'chatbot.pid');
function request(method,pathname,token,body){return new Promise((resolve,reject)=>{const text=body?JSON.stringify(body):null,req=http.request({hostname:'127.0.0.1',port:PORT,method,path:pathname,headers:{...(token?{'X-Admin-Token':token}:{}),...(text?{'Content-Type':'application/json','Content-Length':Buffer.byteLength(text)}:{})}},res=>{let data='';res.on('data',chunk=>data+=chunk);res.on('end',()=>resolve({status:res.statusCode,body:data?JSON.parse(data):{}}));});req.on('error',reject);if(text)req.write(text);req.end();});}
async function main(){
  const original=fs.existsSync(taskPath)?fs.readFileSync(taskPath):null,originalDrafts=fs.existsSync(draftPath)?fs.readFileSync(draftPath):null,originalPid=fs.existsSync(pidPath)?fs.readFileSync(pidPath):null;
  const seed={id:'builder-api-task',normalizedQuestionKey:'builder-api-task',conversationIds:['builder-c1'],question:'Mennyi a szállítási idő?',answer:'',answerSource:'gap',confidenceScore:0,canonicalIds:[],classification:'missing_knowledge',rootCause:'admin_flow_missing',rootCauseReason:'Teszt ok',repairTarget:'admin_intent',estimatedImpact:80,impactBreakdown:{priority:32},topic:'szállítás',priority:'high',businessValue:5,status:'open',occurrenceCount:1,firstSeenAt:'2026-01-01T00:00:00Z',lastSeenAt:'2026-01-01T00:00:00Z',createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'};
  fs.writeFileSync(taskPath,JSON.stringify(seed)+'\n','utf8');fs.writeFileSync(draftPath,'sérült-json-sor\n','utf8');
  const child=spawn(process.execPath,['server.cjs'],{cwd:ROOT,env:{...process.env,PORT:String(PORT),HOST:'127.0.0.1',ADMIN_TOKEN:TOKEN,SUPABASE_URL:'',SUPABASE_SERVICE_ROLE_KEY:'',UNAS_API_KEY:'',UNAS_SYNC_INTERVAL_MS:'0'},stdio:'ignore'});
  try{
    for(let i=0;i<50;i+=1){try{if((await request('GET','/api/status')).status===200)break;}catch{}await new Promise(resolve=>setTimeout(resolve,100));}
    assert.equal((await request('POST','/api/admin/knowledge-tasks/update',null,{id:'x',status:'open'})).status,401);assert.equal((await request('POST',`/api/admin/knowledge-tasks/update?token=${TOKEN}`,null,{id:'x',status:'open'})).status,401);
    const publicStatus=await request('GET','/api/status');assert.equal(JSON.stringify(publicStatus.body).includes('rootCause'),false);assert.equal(JSON.stringify(publicStatus.body).includes('draft'),false);
    const fill=await request('POST','/api/admin/knowledge-tasks/backfill',TOKEN,{write:true});assert.equal(fill.status,500);const list=await request('GET','/api/admin/knowledge-tasks',TOKEN);assert.equal(list.status,200);for(const field of ['rootCause','rootCauseReason','repairTarget','estimatedImpact','impactBreakdown'])assert(Object.hasOwn(list.body.items[0],field));
    const update=await request('POST','/api/admin/knowledge-tasks/update',TOKEN,{id:'builder-api-task',status:'in_review',reviewerNote:'API teszt megjegyzés'});assert.equal(update.status,200);
    assert.equal((await request('POST',`/api/admin/knowledge-drafts/generate?token=${TOKEN}`,null,{taskId:'builder-api-task'})).status,401);
    for(const endpoint of ['/api/admin/knowledge-tasks/backfill','/api/admin/knowledge-drafts/save','/api/admin/knowledge-drafts/status','/api/admin/knowledge-drafts/export','/api/admin/knowledge-gaps/approve','/api/admin/knowledge-gaps/dismiss','/api/admin/import','/api/admin/unas/sync'])assert.equal((await request('POST',`${endpoint}?token=${TOKEN}`,null,{})).status,401,endpoint);
    const generated=await request('POST','/api/admin/knowledge-drafts/generate',TOKEN,{taskId:'builder-api-task'});assert.equal(generated.status,200);assert.equal(generated.body.draft.draftType,'admin_intent');const draft=generated.body.draft;
    const saved=await request('POST','/api/admin/knowledge-drafts/save',TOKEN,{id:draft.id,draftType:draft.draftType,question:draft.question,answer:draft.answer+' Szerkesztve.',keywords:draft.keywords,category:draft.category,canonicalIds:[],confidenceScore:draft.confidenceScore,safetyStatus:draft.safetyStatus,reviewerNote:'belső'});assert.equal(saved.status,200);assert.equal(saved.body.draft.manuallyEdited,true);
    assert.equal((await request('POST','/api/admin/knowledge-drafts/generate',TOKEN,{taskId:'builder-api-task'})).status,409);const regenerated=await request('POST','/api/admin/knowledge-drafts/generate',TOKEN,{taskId:'builder-api-task',overwriteEdited:true});assert.equal(regenerated.status,200);assert.equal(regenerated.body.draft.manuallyEdited,false);
    assert.equal((await request('POST','/api/admin/knowledge-drafts/status',TOKEN,{id:draft.id,generationStatus:'approved_for_import'})).status,200);const exported=await request('POST','/api/admin/knowledge-drafts/export',TOKEN);assert.equal(exported.status,200);assert.equal(exported.body.drafts.length,1);assert.equal(JSON.stringify(exported.body).includes('reviewerNote'),false);const after=await request('GET','/api/admin/knowledge-drafts?taskId=builder-api-task',TOKEN);assert.equal(after.body.draft.generationStatus,'exported');
    console.log('Knowledge Task és Draft admin API tesztek: OK');
  }finally{child.kill('SIGTERM');await new Promise(resolve=>setTimeout(resolve,200));if(original)fs.writeFileSync(taskPath,original);else if(fs.existsSync(taskPath))fs.unlinkSync(taskPath);if(originalDrafts)fs.writeFileSync(draftPath,originalDrafts);else if(fs.existsSync(draftPath))fs.unlinkSync(draftPath);if(originalPid)fs.writeFileSync(pidPath,originalPid);else if(fs.existsSync(pidPath))fs.unlinkSync(pidPath);}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
