'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');const {ORDER_KEY,ATTRIBUTION_ID,reprocessVerifiedOrder}=require('./engine/verified-order-reprocess.cjs');
const {authHeaders,category,failure}=require('./RUN_VERIFIED_ORDER_REPROCESS.cjs');
function fixture({verified=true,verifyOk=true,sku='VDVSZ'}={}){let outcome=null,writes=0,verifyCalls=0;const proof={proof_id:'8a5a7c8f-acbb-48ed-98e9-750f7304e598',verified,verified_at:'2026-08-12T14:10:00.000Z'};const events=[{event_id:crypto.randomUUID(),attribution_id:ATTRIBUTION_ID,event_type:'product_recommended',sku:'VDVSZ',canonical_product_id:'dermavital_szappan',occurred_at:'2026-08-12T14:00:00.000Z'},{event_id:crypto.randomUUID(),attribution_id:ATTRIBUTION_ID,event_type:'product_clicked',sku:'VDVSZ',canonical_product_id:'dermavital_szappan',occurred_at:'2026-08-12T14:01:00.000Z'}];return{proofStore:{findProof:async()=>proof},eventStore:{findAttribution:async()=>events,findProductClickedByAttribution:async()=>events.filter(e=>e.event_type==='product_clicked')},outcomeStore:{insertOutcome:async value=>{if(outcome)return{duplicate:true,outcome};outcome=value;writes++;return{duplicate:false,outcome};}},verifyOrder:async key=>(verifyCalls++,verifyOk?{ok:true,order:{key,id:'365905971',customer:{email:'private@example.test'},items:[{id:'1462570616',sku}]}}:{ok:false}),get writes(){return writes;},get verifyCalls(){return verifyCalls;},get outcome(){return outcome;}};}
(async()=>{const f=fixture();let result=await reprocessVerifiedOrder(f);assert.deepEqual(result,{ok:true,verified:true,duplicate:true});assert.equal(f.verifyCalls,1);assert.equal(f.writes,1);assert.equal(f.outcome.orderKey,ORDER_KEY);assert.equal(f.outcome.attributionId,ATTRIBUTION_ID);assert.equal(/customer|email|phone|address|comment|private@example/i.test(JSON.stringify(f.outcome)),false);result=await reprocessVerifiedOrder(f);assert.deepEqual(result,{ok:true,verified:true,duplicate:true});assert.equal(f.writes,1);
 const missing=fixture({verified:false});await assert.rejects(()=>reprocessVerifiedOrder(missing),/VERIFIED_PROOF_REQUIRED/);assert.equal(missing.verifyCalls,0);assert.equal(missing.writes,0);
 const failed=fixture({verifyOk:false});await assert.rejects(()=>reprocessVerifiedOrder(failed),/UNAS_REVERIFICATION_FAILED/);assert.equal(failed.writes,0);
 const mismatch=fixture({sku:'OTHER'});await assert.rejects(()=>reprocessVerifiedOrder(mismatch),/VERIFIED_OUTCOME_REPROCESS_FAILED/);assert.equal(mismatch.writes,0);
 await assert.rejects(()=>reprocessVerifiedOrder({...fixture(),orderKey:'OTHER'}),/EXACT_REPROCESS_TARGET_REQUIRED/);
 assert.equal(category(401,'commerce_order_proof_lookup'),'SUPABASE_AUTH_FAILED');assert.equal(category(403,'commerce_outcome_insert'),'SUPABASE_PERMISSION_DENIED');assert.equal(category(404,'commerce_attribution_lookup'),'SUPABASE_TABLE_NOT_FOUND');assert.equal(category(404,'revenue_rpc'),'SUPABASE_RPC_NOT_FOUND');assert.equal(category(400,'commerce_outcome_insert'),'SUPABASE_BAD_REQUEST');assert.equal(category(0,'commerce_order_proof_lookup'),'SUPABASE_NETWORK_FAILED');assert.equal(category(500,'commerce_order_proof_lookup'),'SUPABASE_UNKNOWN_REQUEST_FAILED');
 const safe=failure(403,'commerce_outcome_insert');assert.deepEqual({code:safe.code,status:safe.safeStatus,operation:safe.safeOperation},{code:'SUPABASE_PERMISSION_DENIED',status:403,operation:'commerce_outcome_insert'});assert.equal(JSON.stringify(safe).includes('secret'),false);
 const opaque='sb_secret_test-only-value',legacy='eyJ.test-only.service-role';assert.deepEqual(authHeaders(opaque),{apikey:opaque});assert.equal(Object.prototype.hasOwnProperty.call(authHeaders(opaque),'Authorization'),false);assert.deepEqual(authHeaders(legacy),{apikey:legacy,Authorization:`Bearer ${legacy}`});assert.throws(()=>authHeaders(''),/supabase_runtime_required/);
 const cli=fs.readFileSync('RUN_VERIFIED_ORDER_REPROCESS.cjs','utf8');assert.equal(/revenue-phase4|revenue-rpc|insert\s+into/i.test(cli),false);assert.equal(/console\.log\([^\n]*(password|SUPABASE_SERVICE_ROLE_KEY|UNAS_|customer|email|apikey|Authorization)/i.test(cli),false);
 console.log('Exact verified order normal-pipeline reprocess contract: PASS');})().catch(e=>{console.error(e);process.exitCode=1;});
