'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto');const {processOrderProof}=require('./engine/order-proof.cjs');
const attributionId=crypto.randomUUID(),proof={schemaVersion:1,attributionId,orderKey:'99212-298722',timestamp:new Date().toISOString()};
const events=[{event_id:crypto.randomUUID(),attribution_id:attributionId,event_type:'product_recommended',sku:'VDVSZ',canonical_product_id:'dermavital_szappan',occurred_at:new Date(Date.now()-2000).toISOString()},{event_id:crypto.randomUUID(),attribution_id:attributionId,event_type:'product_clicked',sku:'VDVSZ',canonical_product_id:'dermavital_szappan',occurred_at:new Date(Date.now()-1000).toISOString()}];
function stores(){let proofRow=null,outcome=null,writes=0;return{proofStore:{findProof:async()=>proofRow,insertProof:async row=>(proofRow={...row,proof_id:crypto.randomUUID()},{duplicate:false,row:proofRow})},outcomeStore:{insertOutcome:async value=>{if(outcome)return{duplicate:true,outcome};outcome=value;writes++;return{duplicate:false,outcome};}},get outcome(){return outcome;},get writes(){return writes;}};}
const verifyOrder=async key=>({ok:true,order:{key,id:'365905971',customer:{email:'private@example.test'},items:[{id:'1462570616',sku:'VDVSZ'}]}});
(async()=>{const s=stores(),options={proofStore:s.proofStore,outcomeStore:s.outcomeStore,findEvents:()=>events,verifyOrder};let result=await processOrderProof(proof,options);assert.deepEqual(result,{ok:true,verified:true,duplicate:false});assert.equal(s.writes,1);assert.equal(s.outcome.orderKey,proof.orderKey);assert.equal(s.outcome.attributionId,proof.attributionId);assert.equal(s.outcome.orderId,'365905971');assert.equal(/customer|email|phone|address|comment|private@example/i.test(JSON.stringify(s.outcome)),false);result=await processOrderProof(proof,options);assert.deepEqual(result,{ok:true,verified:true,duplicate:true});assert.equal(s.writes,1);
 const failed=stores();result=await processOrderProof({...proof,orderKey:'FAIL'},{proofStore:failed.proofStore,outcomeStore:failed.outcomeStore,findEvents:()=>events,verifyOrder:async()=>({ok:false})});assert.equal(result.error,'unas_verification_failed');assert.equal(failed.writes,0);
 const mismatch=stores();result=await processOrderProof({...proof,orderKey:'MISMATCH'},{proofStore:mismatch.proofStore,outcomeStore:mismatch.outcomeStore,findEvents:()=>events,verifyOrder:async key=>({ok:true,order:{key,id:'1',items:[{id:'x',sku:'OTHER'}]}})});assert.equal(result.verified,false);assert.equal(mismatch.writes,0);
 const missing=stores();await processOrderProof({...proof,orderKey:'NO-STORE'},{proofStore:missing.proofStore,findEvents:()=>events,verifyOrder});result=await processOrderProof({...proof,orderKey:'NO-STORE'},{proofStore:missing.proofStore,findEvents:()=>events,verifyOrder});assert.deepEqual(result,{ok:false,verified:true,duplicate:true,error:'commerce_outcome_storage_failed'});
 console.log('Verified proof outcomeStore production wiring contract: PASS');})().catch(e=>{console.error(e);process.exitCode=1;});
