'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const schema = require('./engine/conversation-decision-transition-schema.cjs');
const policy = require('./engine/conversation-decision-field-policy.cjs');
const { validateTransitionEvent, validateTransitionBatch, validateTransitionProvenance, validateTransitionDependencies, compareTransitionReplay, validateTransitionBase } = require('./engine/conversation-decision-transition-validator.cjs');

function event(overrides = {}) {
  return { contractVersion: 1, eventId: 'event-1', conversationId: 'conversation-1', turnId: 'turn-2', fieldPath: 'resolved.applicationArea', operation: 'SET', eventType: 'FIELD_TRANSITION', eventVersion: 1, stateVersion: 0, baseEnvelopeVersion: 1, baseStateVersion: 0, provenance: { sourceType: 'USER_EXPLICIT', evidenceId: 'e-1' }, payload: 'neck', evidenceIds: ['e-1'], reasonCode: 'CURRENT_TURN_REPLACEMENT', ...overrides };
}
assert.equal(validateTransitionEvent(event()).valid, true);
assert.equal(validateTransitionEvent(event({ operation: 'UNSET', payload: null })).valid, true);
assert.equal(validateTransitionEvent(event({ operation: 'CLEAR', payload: null })).valid, true);
assert.equal(validateTransitionEvent(event({ operation: 'CONFLICT', payload: { candidates: ['scalp', 'neck'] } })).valid, true);
assert.equal(validateTransitionEvent(event({ operation: 'INVALIDATE', payload: { invalidatesFields: ['governance.authorizationStatus'] }, reasonCode: 'DEPENDENCY_INVALIDATED' })).valid, true);
assert.equal(validateTransitionEvent(event({ operation: 'SET', provenance: { sourceType: 'ASSISTANT_OUTPUT_RECOVERY', evidenceId: 'e-1' } })).valid, false);
assert.equal(validateTransitionEvent(event({ operation: 'SET', fieldPath: 'resolved.productFocus', payload: 'product_A', provenance: { sourceType: 'ASSISTANT_OUTPUT_RECOVERY', evidenceId: 'e-1' } })).valid, false);
assert.equal(validateTransitionEvent(event({ operation: 'SET', fieldPath: 'governance.authorizationStatus', payload: 'AUTHORIZED', provenance: { sourceType: 'USER_EXPLICIT', evidenceId: 'e-1' } })).valid, false);
assert.equal(validateTransitionEvent(event({ operation: 'CLEAR', fieldPath: 'governance.scopeId', payload: null, provenance: { sourceType: 'USER_EXPLICIT', evidenceId: 'e-1' } })).valid, false);
assert.equal(validateTransitionEvent(event({ operation: 'CONFLICT', fieldPath: 'governance.authorizationStatus', payload: { candidates: ['AUTHORIZED', 'DENIED'] }, provenance: { sourceType: 'USER_EXPLICIT', evidenceId: 'e-1' } })).valid, false);
assert.equal(validateTransitionEvent(event({ operation: 'SET', fieldPath: 'governance.scopeId', payload: null, provenance: { sourceType: 'CANONICAL_RESOLUTION', evidenceId: 'e-1' } })).valid, false);
assert.equal(validateTransitionEvent(event({ fieldPath: 'resolved.requestedProductType', payload: 'cream' })).valid, true);
assert.equal(validateTransitionEvent(event({ fieldPath: 'resolved.productFocus', payload: 'product_A', provenance: { sourceType: 'USER_EXPLICIT', evidenceId: 'e-1' } })).valid, true);
assert.equal(validateTransitionEvent(event({ fieldPath: 'resolved.productFocus', payload: 'product_A', provenance: { sourceType: 'UNKNOWN', evidenceId: 'e-1' } })).valid, false);
assert.equal(validateTransitionEvent(event({ fieldPath: 'resolved.applicationArea', payload: 'scalp' })).valid, true);
assert.notEqual('neck', 'scalp');
assert.equal(validateTransitionEvent(event({ fieldPath: 'resolved.applicationArea', payload: 'neck', reasonCode: 'CURRENT_TURN_REPLACEMENT' })).valid, true);
assert.equal(validateTransitionEvent(event({ fieldPath: 'resolved.requestedProductType', payload: 'cream' })).valid, true);
assert.equal(validateTransitionEvent(event({ fieldPath: 'resolved.productFocus', payload: 'product_A', provenance: { sourceType: 'CANONICAL_RESOLUTION', evidenceId: 'e-canonical' } })).valid, true);
assert.equal(validateTransitionEvent(event({ fieldPath: 'resolved.concernContext', payload: 'psoriasis', provenance: { sourceType: 'PROBLEM_DOMAIN_DECISION', evidenceId: 'e-domain' } })).valid, true);
assert.equal(validateTransitionEvent(event({ fieldPath: 'explicit.qualifiers', payload: [{ key: 'dry', value: true, evidenceIds: ['e-dry'] }], provenance: { sourceType: 'USER_EXPLICIT', evidenceId: 'e-dry' } })).valid, true);
assert.equal(validateTransitionEvent(event({ fieldPath: 'derived.ownershipState', payload: 'SAFETY', provenance: { sourceType: 'PROBLEM_DOMAIN_DECISION', evidenceId: 'e-safety' } })).valid, true);
assert.equal(validateTransitionEvent(event({ fieldPath: 'derived.ownershipState', payload: 'MEDICAL', provenance: { sourceType: 'PROBLEM_DOMAIN_DECISION', evidenceId: 'e-medical' } })).valid, true);
assert.equal(validateTransitionEvent(event({ fieldPath: 'governance.authorizationStatus', operation: 'INVALIDATE', payload: { invalidatesFields: ['governance.authorizationStatus'] }, reasonCode: 'DEPENDENCY_INVALIDATED' })).valid, false);
assert.equal(validateTransitionEvent(event({ fieldPath: 'resolved.applicationArea', operation: 'INVALIDATE', payload: { invalidatesFields: ['explicit.products'] }, reasonCode: 'DEPENDENCY_INVALIDATED' })).valid, false);
assert.equal(validateTransitionEvent(event({ fieldPath: 'resolved.applicationArea', operation: 'INVALIDATE', payload: { invalidatesFields: ['resolved.applicationArea'] }, reasonCode: 'DEPENDENCY_INVALIDATED' })).valid, false);
assert.equal(validateTransitionEvent(event({ fieldPath: 'resolved.applicationArea', operation: 'INVALIDATE', payload: { invalidatesFields: ['governance.authorizationStatus', 'governance.authorizationStatus'] }, reasonCode: 'DEPENDENCY_INVALIDATED' })).valid, false);
assert.equal(policy.FIELD_PROVENANCE_POLICY['resolved.requestedProductType'].USER_EXPLICIT, 'ADMISSIBLE_CANDIDATE');
assert.equal(policy.FIELD_PROVENANCE_POLICY['governance.authorizationStatus'].USER_EXPLICIT, 'FORBIDDEN');
assert.equal(policy.isRecoveryOnly('LEGACY_TEXT_RECOVERY'), true);
assert.equal(policy.isAuthorizationCapableSource('LEGACY_TEXT_RECOVERY'), false);
assert.equal(policy.isAuthorizationCapableSource('APPROVED_PRODUCT_FACT'), true);
assert.deepEqual(policy.getFieldDependents('resolved.applicationArea'), ['governance']);
assert.equal(schema.TRANSITION_FIELD_PATHS.includes('resolved.requestedProductType'), true);
assert.equal(schema.TRANSITION_OPERATIONS.includes('INVALIDATE'), true);
assert.equal(schema.TRANSITION_OPERATIONS.includes('NOT_A_REAL_OPERATION'), false);
assert.equal(validateTransitionEvent(event({ fieldPath: 'resolved.notAField' })).valid, false);
assert.equal(validateTransitionEvent(event({ contractVersion: 2 })).valid, false);
assert.equal(validateTransitionEvent(event({ eventVersion: 0 })).valid, false);
assert.equal(validateTransitionEvent(event({ operation: 'SET', payload: undefined })).valid, false);
assert.equal(validateTransitionEvent(event({ operation: 'CONFLICT', payload: { candidates: ['one'] } })).valid, false);
assert.equal(validateTransitionEvent(event({ fieldPath: 'resolved.applicationArea', payload: { value: 'neck' } })).valid, false);
assert.equal(validateTransitionEvent(event({ fieldPath: 'resolved.requestedProductType', payload: ['cream'] })).valid, false);
assert.equal(validateTransitionEvent(event({ operation: 'INVALIDATE', payload: { invalidatesFields: ['arbitrary.runtime.path'] }, reasonCode: 'DEPENDENCY_INVALIDATED' })).valid, false);
assert.equal(validateTransitionEvent(event({ operation: 'INVALIDATE', payload: { invalidatesFields: ['governance.*'] }, reasonCode: 'DEPENDENCY_INVALIDATED' })).valid, false);
assert.equal(validateTransitionEvent(event({ fieldPath: 'resolved.requestedProductType', payload: 'cream', provenance: { sourceType: 'APPROVED_PRODUCT_FACT', evidenceId: 'e-fact' } })).valid, false);
assert.equal(validateTransitionEvent(event({ fieldPath: 'explicit.goal', payload: { value: 'selection', evidenceIds: ['e-goal'] }, provenance: { sourceType: 'APPROVED_PRODUCT_FACT', evidenceId: 'e-fact' } })).valid, false);
assert.equal(validateTransitionEvent(event({ fieldPath: 'resolved.productFocus', payload: 'product_A', provenance: { sourceType: 'APPROVED_PRODUCT_FACT', evidenceId: 'e-fact' } })).valid, false);
assert.equal(validateTransitionProvenance(event({ provenance: { sourceType: 'LEGACY_TEXT_RECOVERY', evidenceId: 'e-legacy' }, operation: 'SET' })).valid, false);
assert.equal(validateTransitionDependencies(event({ operation: 'INVALIDATE', fieldPath: 'resolved.applicationArea', payload: { invalidatesFields: ['arbitrary.runtime.path'] } })).valid, false);
assert.equal(compareTransitionReplay(event(), event()).result, 'EXACT_REPLAY');
const nestedA = event({ fieldPath: 'explicit.qualifiers', provenance: { sourceType: 'USER_EXPLICIT', evidenceId: 'e-1', fieldPath: 'explicit.qualifiers', sourceTurnId: 'turn-2' }, payload: [{ key: 'dry', value: true, evidenceIds: ['e-2', 'e-1'] }] });
const nestedB = event({ fieldPath: 'explicit.qualifiers', provenance: { sourceTurnId: 'turn-2', fieldPath: 'explicit.qualifiers', evidenceId: 'e-1', sourceType: 'USER_EXPLICIT' }, payload: [{ evidenceIds: ['e-1', 'e-2'], value: true, key: 'dry' }] });
assert.equal(compareTransitionReplay(nestedA, nestedB).result, 'EXACT_REPLAY');
assert.equal(compareTransitionReplay(event(), event({ payload: 'scalp' })).result, 'EVENT_ID_COLLISION');
assert.equal(compareTransitionReplay(event(), event({ provenance: { sourceType: 'CANONICAL_RESOLUTION', evidenceId: 'e-1' } })).result, 'EVENT_ID_COLLISION');
assert.equal(compareTransitionReplay(event(), event({ eventId: 'event-2' })).result, 'DISTINCT_EVENT');
assert.equal(validateTransitionEvent(event({ operation: 'SET', fieldPath: 'resolved.applicationArea', payload: null })).valid, false);
assert.equal(validateTransitionEvent(event({ operation: 'SET', fieldPath: 'resolved.requestedProductType', payload: null })).valid, false);
assert.equal(validateTransitionEvent(event({ operation: 'SET', fieldPath: 'resolved.productFocus', payload: null })).valid, false);
assert.equal(validateTransitionBase(event({ baseStateVersion: 0, baseEnvelopeVersion: 1 }), 0, 1).result, 'ELIGIBLE');
assert.equal(validateTransitionBase(event({ baseStateVersion: 0, baseEnvelopeVersion: 1 }), 1, 1).result, 'STALE_BASE');
assert.equal(validateTransitionBase(event({ baseStateVersion: 1, baseEnvelopeVersion: 1 }), 0, 1).result, 'FUTURE_BASE');
assert.equal(validateTransitionBase(event({ baseStateVersion: -1, baseEnvelopeVersion: 1 }), 0, 1).result, 'INVALID_BASE');
assert.equal(validateTransitionBatch([event(), event({ eventId: 'event-2' })]).valid, true);
assert.equal(validateTransitionBatch([event(), event()]).valid, false);
const previous = event(); const before = JSON.stringify(previous); validateTransitionEvent(previous); assert.equal(JSON.stringify(previous), before);
const schemaFiles = ['engine/conversation-decision-transition-schema.cjs', 'engine/conversation-decision-transition-validator.cjs', 'engine/conversation-decision-field-policy.cjs'];
for (const file of schemaFiles) {
  const source = fs.readFileSync(path.join(__dirname, file), 'utf8');
  assert.equal(/Date\.now|Math\.random|node:fs|readFileSync|fetch\(|eval\s*\(|new Function|answer-service|answer-router|server\.cjs|product-intelligence-recommendation-scope-repository|authorization-adapter/.test(source), false, file);
}
for (const file of ['answer-service.cjs', 'answer-router.cjs', 'answer-planner.cjs', 'conversation-context.cjs', 'conversation-memory.cjs']) assert.equal(fs.readFileSync(path.join(__dirname, 'engine', file), 'utf8').includes('conversation-decision-transition'), false, file);
assert.equal(fs.readFileSync(path.join(__dirname, 'server.cjs'), 'utf8').includes('conversation-decision-transition'), false);
console.log('Conversation Decision Transition R4A2A: PASS');