'use strict';
const {buildConversationContext}=require('./conversation-context.cjs');
const {normalize}=require('./normalizer.cjs');
const {PRODUCTS}=require('./product-catalog.cjs');
const {detectCustomerGoal}=require('./customer-goal.cjs');
const {createCatalogSearch}=require('./catalog-search.cjs');
const fs=require('fs');
const {resolvePersistedProductEvidence}=require('./persisted-product-evidence.cjs');
const SESSION_RE=/^[a-zA-Z0-9-]{16,100}$/;const MAX_HISTORY_MESSAGES=20;
const catalog=createCatalogSearch();
let canonicalByUnasId={};
let skuByProductId={};
try{const mapping=JSON.parse(fs.readFileSync(require('path').join(__dirname,'..','data','canonical-unas-mapping.json'),'utf8'));const approved=(mapping.mappings||[]).filter(item=>item.mappingStatus==='approved');canonicalByUnasId=Object.fromEntries(approved.filter(item=>item.unasId).map(item=>[String(item.unasId),item.canonicalId]));skuByProductId=Object.fromEntries(approved.flatMap(item=>[[item.canonicalId,item.sku],[String(item.unasId||''),item.sku]]).filter(([,sku])=>sku));}catch{}
function validSessionId(value){return SESSION_RE.test(String(value||''));}
function normalizeMessage(value){if(!value||!['user','assistant'].includes(value.role)||typeof value.content!=='string')return null;const content=value.content.trim().slice(0,5000);if(!content)return null;const links=(Array.isArray(value.links)?value.links:[]).slice(0,3).map(item=>({id:String(item?.id||'').slice(0,80),name:String(item?.name||item?.title||'').slice(0,300)})).filter(item=>item.id);return{role:value.role,content,...(links.length?{links}:{}),...(value.route?{route:String(value.route).slice(0,40)}:{}),...(value.intent?{intent:String(value.intent).slice(0,80)}:{}),...(value.domain?{domain:String(value.domain).slice(0,80)}:{}),...(value.responseType?{responseType:String(value.responseType).slice(0,80)}:{})};}
function rowsToHistory(rows){return[...(Array.isArray(rows)?rows:[])].sort((a,b)=>String(a.created_at||'').localeCompare(String(b.created_at||''))).flatMap(row=>{const user=normalizeMessage({role:'user',content:row.question});const assistant=normalizeMessage({role:'assistant',content:row.answer,route:row.routing_trace?.route,intent:row.routing_trace?.intent,domain:row.routing_trace?.domain,responseType:row.routing_trace?.responseSource||row.source});return[user,assistant].filter(Boolean);});}
function mergeHistory(serverHistory=[],clientHistory=[],limit=MAX_HISTORY_MESSAGES){const out=[],seen=new Set();for(const raw of [...serverHistory,...clientHistory]){const item=normalizeMessage(raw);if(!item)continue;const key=`${item.role}\u0000${item.content}`;if(seen.has(key))continue;seen.add(key);out.push(item);}return out.slice(-Math.max(1,Math.min(Number(limit)||MAX_HISTORY_MESSAGES,MAX_HISTORY_MESSAGES)));}
function renderedProductList(message){if(!message)return[];if(Array.isArray(message.links)&&message.links.length)return message.links.map(item=>canonicalByUnasId[String(item.id)]||String(item.id)).filter(Boolean);const evidence=resolvePersistedProductEvidence(message.content||'');if(evidence.status==='resolved'||evidence.orderedProductIds.length>1)return evidence.orderedProductIds;return[];}
function structuredState(history=[]){const context=buildConversationContext(history,normalize),last=[...history].reverse(),lastUser=last.find(x=>x.role==='user'),lastAssistantIndex=[...history].map((x,index)=>({x,index})).reverse().find(entry=>entry.x.role==='assistant')?.index,lastAssistant=lastAssistantIndex==null?null:history[lastAssistantIndex],precedingUser=lastAssistantIndex==null?null:[...history.slice(0,lastAssistantIndex)].reverse().find(x=>x.role==='user'),rendered=renderedProductList(lastAssistant),ordinal=rendered.length?rendered:context.lastRecommendedProducts||[],assistantFocus=lastAssistant?.focusedProduct||(rendered.length?rendered[0]:null),productContextStatus=context.productContextStatus==='ambiguous'?'ambiguous':ordinal.length>1&&context.productContextStatus!=='resolved'?'ambiguous':assistantFocus||context.lastFocusProduct?'resolved':context.productContextStatus||'unresolved',focusedProductId=assistantFocus||context.lastFocusProduct||null,purchaseProductId=productContextStatus==='resolved'?focusedProductId:null,lastMentionedProduct=focusedProductId,activeProductIds=[...new Set([...(context.mentionedProducts||[]),...ordinal])],activeSkus=[...new Set(activeProductIds.map(id=>skuByProductId[id]||PRODUCTS[id]?.sku).filter(Boolean))],activeProblemDomains=[...new Set([context.lastProblemDomain].filter(Boolean))];return{activeProductIds,activeSkus,activeProblemDomains,lastRecommendedProducts:[...ordinal],lastOrdinalProductList:[...ordinal],selectedProductId:context.lastSelectedProduct||null,focusedProductId,purchaseProductId,productContextStatus,lastMentionedProduct,lastUserIntent:lastUser?.intent||detectCustomerGoal(lastUser?.content||'').intent||null,lastAssistantIntent:lastAssistant?.intent||detectCustomerGoal(precedingUser?.content||'').intent||null,lastCommerceFocus:context.lastCommerceIntent||null};}
async function rehydrateSessionHistory({sessionId,clientHistory=[],loadRows,limit=10}={}){if(!validSessionId(sessionId))return{history:mergeHistory([],clientHistory),state:structuredState(clientHistory),technicalFailure:false};let rows=[];try{rows=await loadRows(sessionId,Math.max(1,Math.min(Number(limit)||10,10)));}catch{return{history:mergeHistory([],clientHistory),state:structuredState(clientHistory),technicalFailure:true};}const serverHistory=rowsToHistory(rows),history=mergeHistory(serverHistory,clientHistory);return{history,state:structuredState(history),technicalFailure:false};}
module.exports={MAX_HISTORY_MESSAGES,validSessionId,normalizeMessage,rowsToHistory,mergeHistory,renderedProductList,structuredState,rehydrateSessionHistory};
